### ISSUE TITLE
Quick start guide on Valoraapp.com 

### ISSUE THREAD

**Issue by vslavich** [celo-org/website#108]
Corey 
we've been working on some designs for a quick start guide on the Valora Support site, it's a fairly small (optional) header to be added to certain support articles to make them more polished and user friendly. The Quick Start Guide, for example, is prompted when the user first joins Valora and it'd be nice to have that experience look a step nicer than the text only Support Articles.

https://www.figma.com/file/QL4cOwKy0BD69QWPTtP7nh/In-app-education?node-id=181%3A18
https://docs.google.com/document/d/1iSbtN3HxaMU_OzNCe2zR4iX8vxeYN3QkpMkBvI6MpJY/edit

**Comment by aaronmgdr** [comment]
A) stylize all the support articles titles as above

B) add optional table of contents fields and type to support article in contentful styled as above.
