### ISSUE TITLE
Public sector page on celo.org

### ISSUE THREAD

**Issue by vslavich** [celo-org/website#109]
https://www.figma.com/file/E7HhqLi5TrFwcCpKriqEu4/Celo-Website-5.0?node-id=21%3A0

Owners are Zeek and Anca

**Comment by laurencedelisle** [comment]
Copy here: https://docs.google.com/document/d/1iOUU7YKfNwEY-7M4mNm5bzK2Gcawuiw62_1pv8J5Szo/edit
