### ISSUE TITLE
Valora Open Graph Images

### ISSUE THREAD

**Issue by tjlahey** [celo-org/website#114]
User currently sees
![image](https://user-images.githubusercontent.com/3344589/110540444-5bb95d80-80db-11eb-84c4-a704af8ba543.png)
![image](https://user-images.githubusercontent.com/3344589/110540453-607e1180-80db-11eb-8fae-937c378e2f2c.png)

User SBAT see for **all** of our Valora web pages.
![image](https://user-images.githubusercontent.com/3344589/110541353-7809ca00-80dc-11eb-8f30-df589144b908.png)

Figma File
https://www.figma.com/file/cuuQDvJFav9hDnqiPrJhTo/Valora-Website-v2?node-id=1570%3A0
![image](https://user-images.githubusercontent.com/3344589/110541380-835cf580-80dc-11eb-911e-7d7ab9b8eea8.png)

**Comment by coreycelo** [comment]
Looks great!
