### ISSUE TITLE
Zip for CELO token is missing rounded version

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/website#129]
STESP TO reproduce 
1. go to https://celo.org/experience/brand/exchange-icons#overview
2. download "CELO Exchange Icon Full Color" 
3. open zip 
4. go to svg folder. only one SVG N

EXPectation

there is an SVG for both circle and square versions

**Comment by jmrossy** [comment]
@aaronmgdr I needed the sexy circle version for celowallet.app so went ahead and made that. Attaching as a .txt file cause Github doesn't allow SVGs for some reason
[CELO.txt](https://github.com/celo-org/website/files/6173486/CELO.txt)

**Comment by aaronmgdr** [comment]
oh I have the canonical file here. 
[CELO.zip](https://github.com/celo-org/website/files/6173810/CELO.zip)
