### ISSUE TITLE
New Section to celo.org/papers + subtitle edit

### ISSUE THREAD

**Issue by laurencedelisle** [celo-org/website#132]
Add a section to the celo.org/papers called "Social Impact" and include the following two papers -- this will also require changing the subtitle:

- https://drive.google.com/file/d/1Sf_jqhE8buy0qtIQiUI9IcfB4IiHGuBG/view?usp=sharing (Policy Paper on Humanitarian Aid)
- https://docs.google.com/document/d/1ezwvPPN9z0HtIaB_KvLFM3F-SuekevlQlFOv0aO6DQ8/edit (Write up/full report on the Grameen Pilot)

Will also need to change the subtitle -- right now it says paper on protocol and economics

Submitted by Will Le

**Comment by laurencedelisle** [comment]
Needs to be done before the next Kuneco -- April 22nd, 2021

**Comment by laurencedelisle** [comment]
Subtitle: Papers on Celo Protocol, Economics, & Use Cases

Paper One Title: Future-Proof Aid Policy
Paper Two Title: Delivering Humanitarian COVID Aid using the Celo Platform

**Comment by aaronmgdr** [comment]
Link directly to the files
