### ISSUE TITLE
Add a Valora Blog to the Website

### ISSUE THREAD

**Issue by laurencedelisle** [celo-org/website#133]
In the scoping phase https://docs.google.com/document/d/1a1PHma5BybmTnZ5F4IEdO6Fx4ba7MjJPR1ejYOLAO0A/edit#

design https://www.figma.com/file/H2V4imYdqtmOKOaWCcUQdY/Valora-Blog?node-id=0%3A1&viewport=956%2C676%2C0.14491547644138336

**Comment by laurencedelisle** [comment]
In the design phase

**Comment by aaronmgdr** [comment]
closing in favor of smaller tickets
