### ISSUE TITLE
Terms  are not updating on contentful valoraapp.com

### ISSUE THREAD

**Issue by laurencedelisle** [celo-org/website#144]
Some of the content on valoraapp is not updating.

The date on the Terms page for spanish, should be december, not july  (subSection - Terms Title and Date) https://valoraapp.com/es/terms
The content on the Terms page for Portuguese, should show Portugeuese content not English  (FreeContent - cLabs Terms)
https://valoraapp.com/pt/terms

**Comment by aaronmgdr** [comment]
Valorapp.com terms still come from a markdown file.  the terms  on contentful are used on clabs.co 

SOLUTION: make valorapp.com use same terms  from contenful. as cLabs.co 


Took me a minute to remember this myself.
