### ISSUE TITLE
Expand functionality of  Attention Component in Contentful  

### ISSUE THREAD

**Issue by laurencedelisle** [celo-org/website#145]
I’d like to use the attention component but be able to add other rich content. Right now I can’t add bullet points or links.

Example of where: https://preview-dot-clabs-valora-web.uc.r.appspot.com/support/transfer-funds-from-coinbase-to-valora

When I try to add bullet points and links in the attention component/entry I get a warning and I’m not allowed to publish.

**Comment by aaronmgdr** [comment]
might need to modify code to support this. then after that its just a matter of turning on options in contentful content model
