### ISSUE TITLE
Update messaging on celo.org for cEUR passing

### ISSUE THREAD

**Issue by laurencedelisle** [celo-org/website#150]
look at 
- Home page
- Brand Kit 
- Audit of website 
- New languaging 
- Optimal: program it in and when we go live we deploy the changes 

Laurence working with comms w Lilly

**Comment by aaronmgdr** [comment]
look at 
- Home page
- Brand Kit 
- Audit of website 
- New languaging 
- Optimal: program it in and when we go live we deploy the changes 

Laurence working with comms w Lilly
