### ISSUE TITLE
Update cLabs Glyph on clabs.co

### ISSUE THREAD

**Issue by tjlahey** [celo-org/website#209]
**User SBAT**
Adjusted cLabs Glyph in the mobile header icon, universal footer, and website hero
![image](https://user-images.githubusercontent.com/3344589/121411676-c0719780-c918-11eb-80fc-fe268ae880aa.png)
![image](https://user-images.githubusercontent.com/3344589/121411698-c5364b80-c918-11eb-85c8-449603229d33.png)
![image](https://user-images.githubusercontent.com/3344589/121412698-da5faa00-c919-11eb-8aef-a1ef38d80f7b.png)

Figma Link:
[https://www.figma.com/file/qOTzIslwDIH6cHaqUGdaHb/?node-id=458%3A87](https://www.figma.com/file/qOTzIslwDIH6cHaqUGdaHb/?node-id=458%3A87)

Graphics is resized and put in to a container for your developing ease.

HMU if you need any support.

**Comment by michellewong793** [comment]
file for header updated as of 6/14/2021
![image.png](https://images.zenhubusercontent.com/5fd25adf27e82713828ef0be/7d6f5f13-04e8-4b61-8e76-e261c38acbdb)

**Comment by michellewong793** [comment]
updated glyph on mobile as well: 

![image.png](https://images.zenhubusercontent.com/5fd25adf27e82713828ef0be/85665539-536a-4d53-8986-83602cec0afc)

**Comment by michellewong793** [comment]
glyph is subsequently updated in the mobile footer as well 
![image.png](https://images.zenhubusercontent.com/5fd25adf27e82713828ef0be/783d9ad1-9ddf-466b-b227-d792171622ba)

**Comment by michellewong793** [comment]
this has been committed to the clabs repo - this just needs to be deployed now @aaronmgdr
