### ISSUE TITLE
Top Nav changes on celo.org 

### ISSUE THREAD

**Issue by albertomartin** [celo-org/website#234]
Old Navigation / Current: (8 + 2 icons)
About |  Join |  Validators | Developers | Alliance | Community | Blog  | GitHub

New Navigation ( 4 + 2 icons) 
About | Developers | Community | Alliance |  {Blog icon M} |  {Github icon}

**Comment by tjlahey** [comment]
Header preview

![image.png](https://images.zenhubusercontent.com/60c7b08859f59e00242486fb/f74713b1-9d1a-41ec-aba4-346240a5eda3)
