### ISSUE TITLE
Makes changes to the celo.org footer 

### ISSUE THREAD

**Issue by albertomartin** [celo-org/website#235]
Keep: 

- Home
- About
- Careers 
- Validators
- Developers
- Alliance
- Community
- Annual Report

✅   ~Remove: Defi Pulse from this list~ (done)

- Blog
- GitHub
- Twitter
- Forum
- Chat
- YouTube
- Instagram
- Defi Pulse <--- It does not list Celo
- LinkedIn
- Twitch
- Reddit
- Telegram

**Comment by tjlahey** [comment]
**Figma**
https://www.figma.com/file/E7HhqLi5TrFwcCpKriqEu4/?node-id=43%3A0

**Preview**
![image.png](https://images.zenhubusercontent.com/60c7b08859f59e00242486fb/ec6389ca-a645-4938-9c8b-d6c6cd23615f)
