### ISSUE TITLE
 Update Stats Widget on homepage 

### ISSUE THREAD

**Issue by albertomartin** [celo-org/website#237]
On the Platform Stats, we should remove the Total Addresses seems to be wrong: 
https://bit.ly/3fSym54 has 1M, but on the main page of explorer we have 700k

Adding Marek, in case he thinks we should keep at the 1M. 

IMO we should have: 
1. Total blocks (OR Total Transactions) 
2. Avg block time
3. Days of Carbon positive

**Comment by aaronmgdr** [comment]
isnt equally possible that thecelo.com stat is wrong?

**Comment by tjlahey** [comment]
Preview of the latest. Waiting to hear back on Transactions vs blocks, and 

![image.png](https://images.zenhubusercontent.com/60c7b08859f59e00242486fb/024bfa60-3ef1-43ed-8881-d8d71c742d4f)![image.png](https://images.zenhubusercontent.com/60c7b08859f59e00242486fb/4346f942-1a91-48ec-9d66-5a1fa2c18a90)

**Comment by aaronmgdr** [comment]
@albertomartin  do we have a discision on Blocks vs Transations?

**Comment by albertomartin** [comment]
Days of Carbon Negative: days since April 27 2020.
Lets do Transactions
