### ISSUE TITLE
Home Page - Below the fold - What is Celo

### ISSUE THREAD

**Issue by albertomartin** [celo-org/website#242]
https://www.figma.com/proto/E7HhqLi5TrFwcCpKriqEu4/Celo-Website-5.0?page-id=43%3A0&node-id=1236%3A0&viewport=-254%2C1419%2C0.2768425941467285&scaling=min-zoom 

[Header: ]
What is Celo? 

Sections 
- Mobile
- Open
- Real

**Comment by tjlahey** [comment]
[Header: ]
What is Celo?
![image.png](https://images.zenhubusercontent.com/60c7b08859f59e00242486fb/256447fd-407f-486a-b3d9-e38f11df0b21)

[Subsection:] Meet the Celo Community
![image.png](https://images.zenhubusercontent.com/60c7b08859f59e00242486fb/c10e98a4-af5f-45ef-8e26-4797ca57e41a)
