### ISSUE TITLE
Home page meet community section

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/website#245]
[Subsection:] Meet the Celo Community
![image.png](https://images.zenhubusercontent.com/60c7b08859f59e00242486fb/c10e98a4-af5f-45ef-8e26-4797ca57e41a)

[Subsection:] Meet the celo community

Backers of the Celo ecosystem and holders of CELO include a16z, Polychain Capital, General Catalyst, Coinbase, Social Capital, Reid Hoffman, Jack Dorsey, Naval Ravikant, and many more.

[Icons 3 rows: 3 items per row] 
a16z | Polychain | General ...
Coinbase | Social ... | Read Hoffman |
|J Dorsey | Naval ... | Many more 

Learn More > [link to “What is Celo?” page]

**Comment by tjlahey** [comment]
@Henrynunez112 FYI - please re-upload all of these icons from figma @2x, I color corrected these icons to be Celo light (#ffffff) or pure white.

**Comment by Henrynunez112** [comment]
Got it!!

**Comment by michellewong793** [comment]
where is the "What is Celo?" page ?
