### ISSUE TITLE
HomePage Above the Fold

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/website#250]
![Screen Shot 2021-06-24 at 11.35.56 AM.png](https://images.zenhubusercontent.com/5fb2afa5956d0afea1d2ff48/d8b4f8ab-f22b-46ce-bb78-c4ab7fb6e55f)

*header*
Crypto Made for Mobile

*Description*
Celo is a mobile-first blockchain that makes financial dApps and crypto payments accessible to anyone with a mobile phone

**Comment by tjlahey** [comment]
@aaronmgdr note the Celo Dark gradient background fade in the press section as it overlaps the Celo Coin milky way.

I'll be available for supporting you to get it right.
