### ISSUE TITLE
Images on /dapps page are squeezed

### ISSUE THREAD

**Issue by albertomartin** [celo-org/website#280]
Seems that now the images are constrained by certain dimensions and all of them are squeezed. If we have to re-cut, make them all the same, we can create a simple 1px dot in each corner to make them (e.g 200x150)

 ![Screen Shot 2021-07-13 at 7.47.21 PM.png](https://images.zenhubusercontent.com/60b7e6d68e6f421a205490b3/b23f0418-ed45-4847-95fd-d655165cb8e6)

**Comment by aaronmgdr** [comment]
ha you must have seen this yesterday around 6pm. all fixed now
