### ISSUE TITLE
Align side h3 to body content (universal bug)

### ISSUE THREAD

**Issue by tjlahey** [celo-org/website#30]
### Expected Behavior

It's sorta tough to catch but the h3 on the left is above the beginning of the paragraph text on the right. 

### Current Behavior

![image](https://user-images.githubusercontent.com/3344589/81855597-6aaf9d80-9514-11ea-8f2c-08df50014097.png)

**Comment by michellewong793** [comment]
gotcha

**Comment by michellewong793** [comment]
this has been difficult to implement, since we have global styles for h3's and different font sizes for each body content. so far, i've been thinking about changing the line height of the h3 to match the body content's, but this doesn't work for every case. thoughts?

**Comment by michellewong793** [comment]
after talking to taylor about what works, we can work towards just aligning at the top of the text, rather than the baseline, which is still a challenge, but better than baseline

**Comment by michellewong793** [comment]
going to set that as a wont fix for now since the only thing that will help out would be custom css for each h3
