### ISSUE TITLE
Updated Public Page needed - Mirroring contentul

### ISSUE THREAD

**Issue by albertomartin** [celo-org/website#326]
Needs to be published by 9/28
Preliminary: https://www.figma.com/file/E7HhqLi5TrFwcCpKriqEu4/Celo-Website-5.0?node-id=21%3A0 

Announcement at 10:20 am EST 
Copy / logic here: 
https://docs.google.com/document/d/1mwQ3W9cg37Ej7tFMNG_EtucOu-jpexXdSa8JmzKC_bE/edit

**Comment by Henrynunez112** [comment]
Hidden features to allow publishing on a specific day
