### ISSUE TITLE
Marketing/PR team requesting 3 actions as part of the ramp-up to the forbes event.

### ISSUE THREAD

**Issue by albertomartin** [celo-org/website#341]
[due: 9/7]
1. Add the public sector page to the CeloOrg toolbar
2. Add a banner to cLabs.co driving traffic to the Forbes event - UTM LINK HERE
3. Add a banner to Celo.org driving traffic to the Forbes event - UTM LINK HERE

[PM Approved]
#1. 

Rejected 
#2: https://www.forbes.com/connect/events/celo-future-of-cbdcs-and-cryptocurrency?promo=SPNCELO&tr=true&utm_source=clabs&utm_medium=site-banner&utm_campaign=forbes-cbdc 
#3: https://www.forbes.com/connect/events/celo-future-of-cbdcs-and-cryptocurrency?promo=SPNCELO&tr=true&utm_source=celoorg&utm_medium=site-banner&utm_campaign=forbes-cbdc 

Rational 
The Celo main page should be a clean destination page, if we are going to have recurring events/news that we want to start adding weekly/monthly we should build a way to do so and get it approved with all stakeholders. (e.g a carrousel view vs static right now)

**Comment by albertomartin** [comment]
The name is "Government"
Location: 
About
Developers
Community
Ecosystem
Alliance 
<--- Here
M (icon)
Github (icon)

**Comment by albertomartin** [comment]
On the Nav Bar the exact words: Government

**Comment by aaronmgdr** [comment]
implemented by #343
