### ISSUE TITLE
Update celo Dark Color

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/website#453]
new hex #111214. This would affect the Celo website, icons (on Light background). 

1. Any icons that are dark need to have new hex 

Pages: 
Alliance, Validators 

all css uses will be changed in our colors enum 

illustrations such as on the /dapps, /public-sector, /buy

**Comment by Henrynunez112** [comment]
Icons: https://www.figma.com/file/E7HhqLi5TrFwcCpKriqEu4/Celo-Website-5.0?node-id=2678%3A10551
