### ISSUE TITLE
Use cREAL instead of cBRL

### ISSUE THREAD

**Issue by tanknimit** [celo-org/website#485]
The Brazil team has confirmed (per Taylor) that we need to use the cREAL ticker instead of cBRL. To reflect this, we need:

1) Update the name on the BrandKit webpage from cBRL to cREAL
2) Update the asset names in the file names. They currently all start with "cBRL"

Background context:
The original team thought the naming would be cBRL, but with a last minute change we should use cREAL.

Can we think of any other areas where cBRL exists that we can replace with cREAL?

**Comment by Henrynunez112** [comment]
check celo.org/brand

**Comment by tanknimit** [comment]
The Brazil team has confirmed (per Taylor) that we need to use the cREAL ticker instead of cBRL. To reflect this, we need:

1) Update the name on the BrandKit webpage from cBRL to cREAL
2) Update the asset names in the file names. They currently all start with "cBRL"

Background context: 
The original team thought the naming would be cBRL, but with a last minute change we should use cREAL. 

Can we think of any other areas where cBRL exists that we can replace with cREAL?
