### ISSUE TITLE
[TBD] New Enterprise Page

### ISSUE THREAD

**Issue by tanknimit** [celo-org/website#486]
New Enterprise focused page on Celo.org

Details/content being flushed out so treat as placeholder.

**Comment by Henrynunez112** [comment]
Tracker list. Be ready by Global World Conf. Mid Feb.

**Comment by tanknimit** [comment]
Update: This will be needed by end of next week. Design/Marketing is working on providing us final design/layout by EOD Tuesday, Dec 14th to have it ready by EOD Friday of next week. 

The layout will be very simple, similar to Government page.

**Comment by Henrynunez112** [comment]
Contact form.
