### ISSUE TITLE
Revamp the featured people on the about page

### ISSUE THREAD

**Issue by cmcewen** [celo-org/website#81]

**Comment by vslavich** [comment]
On Celo.org/ community, have a profile / feature view

- name
- photo
- country (flag)
- why I am a part of Celo
- Contributions I've made to Celo
- button to Airtable form to add yours
- (approval on the backend)

**Comment by vslavich** [comment]
how do people edit?

**Comment by vslavich** [comment]
make it clear it is only for active contributors
