### ISSUE TITLE
Add Trees Saved / Carbon Offsetting to Stats on Celo.org

### ISSUE THREAD

**Issue by vslavich** [celo-org/website#87]
Look into API from project wren to get celo's carbon offset number at the bottom of homepage stats widget.

“a little late but you can GET /offset-orders with your wren API token to get all of the offsets Celo has done. you will have to sum the tons of each offset order to get total carbon offset. hope this helps!”

ask Landon if she knows about api key

**Comment by aaronmgdr** [comment]
asked Amy about api key, she directed me to Landon.

**Comment by aaronmgdr** [comment]
Laurance to handle getting key

**Comment by laurencedelisle** [comment]
We don't have something easy out of the box for getting trees saved—the closest thing we have is a way to get the amount of CO2 offset, e.g. by hitting our /offset-orders endpoint

Here's also a doc on an embeddable badge you could use: https://www.notion.so/Wren-Badge-a1141624a25d4a35a05723496036a8db

Here's Celo's profile page on Wren for reference: https://www.wren.co/profile/celo

And lastly, Celo's API token is af8f3b0d-5d73-4f67-8bec-03d63a1437dd

How does this all sound? I could look into adding an endpoint for getting more impact-related metrics like number of trees saved if that's of interest! :)

**Comment by laurencedelisle** [comment]
Ready for Aaron

**Comment by aaronmgdr** [comment]
https://github.com/bstanfield/wren-api-tutorial
