### ISSUE TITLE
Celo.org/jobs

### ISSUE THREAD

**Issue by vslavich** [celo-org/website#93]
Open community jobs board
Inspiration: https://jobs.cosmos.network/

**Comment by vslavich** [comment]
Connect APIs of community ATS. 
Goal: find jobs to work on projects in the Celo ecosystem

No one should manage it -- minimal viable human input

Target launch: 2nd half of 2021

**Comment by vslavich** [comment]
MVP could be links to other job boards

**Comment by aaronmgdr** [comment]
https://jobs.lever.co/Moola
